import { describe, expect, it, vi } from "vitest";

import { AccessRole, PermissionId } from "../../server/lib/authz.js";
import { SecurityEventSeverity } from "../../server/lib/security-events.js";
import { registerUserManagementRoutes } from "../../server/routes/user/register-user-management-routes.js";

const cloneJson = (value) => JSON.parse(JSON.stringify(value));

const createAppRecorder = () => {
  const routes: Array<{
    method: string;
    path: string;
    handlers: Array<(...args: any[]) => unknown>;
  }> = [];
  const register =
    (method: string) =>
    (path: string, ...handlers: Array<(...args: any[]) => unknown>) => {
      routes.push({
        handlers,
        method,
        path,
      });
    };

  return {
    app: {
      delete: register("DELETE"),
      post: register("POST"),
      put: register("PUT"),
    },
    routes,
  };
};

const getRoute = (routes, method, path) =>
  routes.find((route) => route.method === method && route.path === path);

const createMockRes = () => ({
  body: null as any,
  statusCode: 200,
  status(code) {
    this.statusCode = code;
    return this;
  },
  json(payload) {
    this.body = payload;
    return this;
  },
});

const invokeFinalHandler = async (route, req) => {
  const res = createMockRes();
  await route.handlers[route.handlers.length - 1](req, res);
  return res;
};

const createDependencies = ({ app, overrides = {} }) => ({
  AccessRole,
  BASIC_PROFILE_FIELDS: [
    "name",
    "phrase",
    "bio",
    "email",
    "avatarUrl",
    "avatarDisplay",
    "socials",
    "favoriteWorks",
  ],
  PermissionId,
  SecurityEventSeverity: { WARNING: "warning" },
  app,
  appendAuditLog: vi.fn(),
  applyOwnerRole: vi.fn((user) => user),
  buildUserProfileRevisionToken: vi.fn(() => "revision-token"),
  can: vi.fn(({ permissionId }) => permissionId === PermissionId.USUARIOS),
  defaultPermissionsForRole: vi.fn(() => ["default"]),
  emitSecurityEvent: vi.fn(),
  ensureNoEditConflict: vi.fn(() => true),
  getPrimaryOwnerId: vi.fn(() => "owner-1"),
  getUserAccessContextById: vi.fn(() => ({
    accessRole: AccessRole.NORMAL,
    grants: {},
    isOwner: false,
    isPrimaryOwner: false,
  })),
  isAdminUser: vi.fn(() => false),
  isBasicProfileField: vi.fn((field) =>
    [
      "name",
      "phrase",
      "bio",
      "email",
      "avatarUrl",
      "avatarDisplay",
      "socials",
      "favoriteWorks",
    ].includes(field),
  ),
  isOwner: vi.fn((id) => String(id) === "owner-1"),
  isPrimaryOwner: vi.fn((id) => String(id) === "owner-1"),
  isRbacV2Enabled: true,
  loadOwnerIds: vi.fn(() => ["owner-1", "owner-2"]),
  loadUploads: vi.fn(() => []),
  loadUsers: vi.fn(() => []),
  normalizeAccessRole: vi.fn((value, fallback) => value || fallback),
  normalizeAvatarDisplay: vi.fn((value) => value || { x: 0, y: 0, zoom: 1, rotation: 0 }),
  normalizeUsers: vi.fn((users) => users),
  parseEditRevisionOptions: vi.fn(() => ({})),
  persistCurrentUsers: vi.fn(({ users }) => users),
  pickBasicProfilePatch: vi.fn((update) => update),
  removeOwnerRoleLabel: vi.fn((roles) => roles),
  requireAuth: vi.fn((_req, _res, next) => next?.()),
  resolveDiscordAvatarFallbackUrl: vi.fn(() => null),
  sanitizeFavoriteWorksByCategory: vi.fn((value) => value || []),
  sanitizePermissionsForStorage: vi.fn((value) => value || []),
  sanitizeSocials: vi.fn((value) => value || []),
  shouldEmitSecurityRuleEvent: vi.fn(() => true),
  syncSessionUserDisplayProfile: vi.fn(),
  userWithAccessForResponse: vi.fn((user) => user),
  withEffectiveAvatarUrl: vi.fn((user) => user),
  withUserProfileRevision: vi.fn((user) => user),
  writeOwnerIds: vi.fn(),
  ...overrides,
});

describe("registerUserManagementRoutes", () => {
  it("creates a managed user with autogenerated internal id when email is provided and id is empty", async () => {
    const { app, routes } = createAppRecorder();
    const persistCurrentUsers = vi.fn(({ users }) => users);
    const dependencies = createDependencies({
      app,
      overrides: {
        persistCurrentUsers,
        getUserAccessContextById: vi.fn(() => ({
          accessRole: AccessRole.OWNER_PRIMARY,
          grants: { manage: true },
          isOwner: true,
          isPrimaryOwner: true,
        })),
        can: vi.fn(({ permissionId }) => permissionId === PermissionId.USUARIOS),
      },
    });

    registerUserManagementRoutes(dependencies);

    const route = getRoute(routes, "POST", "/api/users");
    const res = await invokeFinalHandler(route, {
      body: {
        id: "",
        name: "Alice",
        email: "Alice@Example.com",
      },
      session: { user: { id: "owner-1" } },
    });

    expect(res.statusCode).toBe(201);
    expect(res.body.user).toEqual(
      expect.objectContaining({
        id: expect.stringMatching(/^user_[a-f0-9]{32}$/),
        name: "Alice",
        email: "alice@example.com",
      }),
    );
    expect(persistCurrentUsers).toHaveBeenCalledWith(
      expect.objectContaining({
        users: expect.arrayContaining([
          expect.objectContaining({
            id: expect.stringMatching(/^user_[a-f0-9]{32}$/),
            name: "Alice",
            email: "alice@example.com",
          }),
        ]),
      }),
    );
  });

  it("requires email or discord id when creating a managed user", async () => {
    const { app, routes } = createAppRecorder();
    const dependencies = createDependencies({
      app,
      overrides: {
        getUserAccessContextById: vi.fn(() => ({
          accessRole: AccessRole.OWNER_PRIMARY,
          grants: { manage: true },
          isOwner: true,
          isPrimaryOwner: true,
        })),
        can: vi.fn(({ permissionId }) => permissionId === PermissionId.USUARIOS),
      },
    });

    registerUserManagementRoutes(dependencies);

    const route = getRoute(routes, "POST", "/api/users");
    const res = await invokeFinalHandler(route, {
      body: {
        id: "",
        name: "Alice",
        email: "",
        discordUserID: "",
      },
      session: { user: { id: "owner-1" } },
    });

    expect(res.statusCode).toBe(400);
    expect(res.body).toEqual({ error: "email_or_discord_id_required" });
  });

  it("creates a managed user with only discord id and no email", async () => {
    const { app, routes } = createAppRecorder();
    const persistCurrentUsers = vi.fn(({ users }) => users);
    const dependencies = createDependencies({
      app,
      overrides: {
        persistCurrentUsers,
        getUserAccessContextById: vi.fn(() => ({
          accessRole: AccessRole.OWNER_PRIMARY,
          grants: { manage: true },
          isOwner: true,
          isPrimaryOwner: true,
        })),
        can: vi.fn(({ permissionId }) => permissionId === PermissionId.USUARIOS),
      },
    });

    registerUserManagementRoutes(dependencies);

    const route = getRoute(routes, "POST", "/api/users");
    const res = await invokeFinalHandler(route, {
      body: {
        id: "",
        name: "Alice",
        email: "",
        discordUserID: "123456789012345678",
      },
      session: { user: { id: "owner-1" } },
    });

    expect(res.statusCode).toBe(201);
    expect(res.body.user).toEqual(
      expect.objectContaining({
        id: expect.stringMatching(/^user_[a-f0-9]{32}$/),
        name: "Alice",
        email: null,
        discordUserID: "123456789012345678",
      }),
    );
    expect(persistCurrentUsers).toHaveBeenCalledWith(
      expect.objectContaining({
        users: expect.arrayContaining([
          expect.objectContaining({
            id: expect.stringMatching(/^user_[a-f0-9]{32}$/),
            name: "Alice",
            email: null,
            discordUserID: "123456789012345678",
          }),
        ]),
      }),
    );
  });

  it("creates a managed user with both email and discord id", async () => {
    const { app, routes } = createAppRecorder();
    const persistCurrentUsers = vi.fn(({ users }) => users);
    const dependencies = createDependencies({
      app,
      overrides: {
        persistCurrentUsers,
        getUserAccessContextById: vi.fn(() => ({
          accessRole: AccessRole.OWNER_PRIMARY,
          grants: { manage: true },
          isOwner: true,
          isPrimaryOwner: true,
        })),
        can: vi.fn(({ permissionId }) => permissionId === PermissionId.USUARIOS),
      },
    });

    registerUserManagementRoutes(dependencies);

    const route = getRoute(routes, "POST", "/api/users");
    const res = await invokeFinalHandler(route, {
      body: {
        id: "",
        name: "Alice",
        email: "alice@example.com",
        discordUserID: "123456789012345678",
      },
      session: { user: { id: "owner-1" } },
    });

    expect(res.statusCode).toBe(201);
    expect(res.body.user).toEqual(
      expect.objectContaining({
        id: expect.stringMatching(/^user_[a-f0-9]{32}$/),
        name: "Alice",
        email: "alice@example.com",
        discordUserID: "123456789012345678",
      }),
    );
  });

  it("blocks secondary owners from reordering owner accounts", async () => {
    const { app, routes } = createAppRecorder();
    const users = [
      { id: "owner-1", order: 0, status: "active" },
      { id: "owner-2", order: 1, status: "active" },
      { id: "user-1", order: 2, status: "active" },
    ];
    const dependencies = createDependencies({
      app,
      overrides: {
        loadUsers: vi.fn(() => cloneJson(users)),
        getUserAccessContextById: vi.fn(() => ({
          accessRole: AccessRole.OWNER_SECONDARY,
          grants: { manage: true },
          isOwner: true,
          isPrimaryOwner: false,
        })),
        can: vi.fn(({ permissionId }) => permissionId === PermissionId.USUARIOS),
      },
    });

    registerUserManagementRoutes(dependencies);

    const route = getRoute(routes, "PUT", "/api/users/reorder");
    const res = await invokeFinalHandler(route, {
      body: {
        orderedIds: ["owner-2", "owner-1", "user-1"],
      },
      session: { user: { id: "owner-2" } },
    });

    expect(res.statusCode).toBe(403);
    expect(res.body).toEqual({ error: "owner_reorder_forbidden" });
    expect(dependencies.persistCurrentUsers).not.toHaveBeenCalled();
  });

  it("blocks RBAC admin permission updates", async () => {
    const { app, routes } = createAppRecorder();
    const users = [
      {
        id: "admin-1",
        accessRole: AccessRole.ADMIN,
        avatarDisplay: { x: 0, y: 0, zoom: 1, rotation: 0 },
        favoriteWorks: [],
        permissions: [],
        roles: [],
        status: "active",
        socials: [],
      },
      {
        id: "user-2",
        accessRole: AccessRole.NORMAL,
        avatarDisplay: { x: 0, y: 0, zoom: 1, rotation: 0 },
        favoriteWorks: [],
        permissions: ["posts"],
        roles: ["reviewer"],
        status: "active",
        socials: [],
      },
    ];
    const dependencies = createDependencies({
      app,
      overrides: {
        loadUsers: vi.fn(() => cloneJson(users)),
        getUserAccessContextById: vi.fn((userId) => {
          if (String(userId) === "admin-1") {
            return {
              accessRole: AccessRole.ADMIN,
              grants: { admin: true },
              isOwner: false,
              isPrimaryOwner: false,
            };
          }
          return {
            accessRole: AccessRole.NORMAL,
            grants: {},
            isOwner: false,
            isPrimaryOwner: false,
          };
        }),
        can: vi.fn(({ permissionId }) => permissionId === PermissionId.USUARIOS),
      },
    });

    registerUserManagementRoutes(dependencies);

    const route = getRoute(routes, "PUT", "/api/users/:id");
    const res = await invokeFinalHandler(route, {
      body: {
        permissions: ["uploads"],
      },
      params: { id: "user-2" },
      session: { user: { id: "admin-1" } },
    });

    expect(res.statusCode).toBe(403);
    expect(res.body).toEqual({ error: "owner_permission_required" });
    expect(dependencies.persistCurrentUsers).not.toHaveBeenCalled();
  });

  it("emits RBAC privilege escalation warnings with the configured severity", async () => {
    const { app, routes } = createAppRecorder();
    const users = [
      {
        id: "owner-1",
        accessRole: AccessRole.OWNER_PRIMARY,
        avatarDisplay: { x: 0, y: 0, zoom: 1, rotation: 0 },
        favoriteWorks: [],
        name: "Owner",
        permissions: ["*"],
        phrase: "",
        roles: [],
        status: "active",
        socials: [],
      },
      {
        id: "user-2",
        accessRole: AccessRole.NORMAL,
        avatarDisplay: { x: 0, y: 0, zoom: 1, rotation: 0 },
        favoriteWorks: [],
        name: "User",
        permissions: ["posts"],
        phrase: "",
        roles: ["reviewer"],
        status: "active",
        socials: [],
      },
    ];
    const dependencies = createDependencies({
      app,
      overrides: {
        SecurityEventSeverity: { WARNING: "rbac-warning-sentinel" },
        loadUsers: vi.fn(() => cloneJson(users)),
        getUserAccessContextById: vi.fn((userId) => {
          if (String(userId) === "owner-1") {
            return {
              accessRole: AccessRole.OWNER_PRIMARY,
              grants: { manage: true },
              isOwner: true,
              isPrimaryOwner: true,
            };
          }
          return {
            accessRole: AccessRole.NORMAL,
            grants: {},
            isOwner: false,
            isPrimaryOwner: false,
          };
        }),
        can: vi.fn(({ permissionId }) => permissionId === PermissionId.USUARIOS),
      },
    });

    registerUserManagementRoutes(dependencies);

    const route = getRoute(routes, "PUT", "/api/users/:id");
    const res = await invokeFinalHandler(route, {
      body: {
        permissions: ["analytics"],
      },
      params: { id: "user-2" },
      session: { user: { id: "owner-1" } },
    });

    expect(res.statusCode).toBe(200);
    expect(dependencies.emitSecurityEvent).toHaveBeenCalledWith(
      expect.objectContaining({
        type: "privilege_escalation_warning",
        severity: "rbac-warning-sentinel",
        actorUserId: "owner-1",
        targetUserId: "user-2",
        data: expect.objectContaining({
          permissionsBefore: ["posts"],
          permissionsAfter: ["analytics"],
        }),
      }),
    );
  });

  it("falls back to the canonical warning severity when the injected map is unavailable", async () => {
    const { app, routes } = createAppRecorder();
    const users = [
      {
        id: "owner-1",
        accessRole: AccessRole.OWNER_PRIMARY,
        avatarDisplay: { x: 0, y: 0, zoom: 1, rotation: 0 },
        favoriteWorks: [],
        name: "Owner",
        permissions: ["*"],
        phrase: "",
        roles: [],
        status: "active",
        socials: [],
      },
      {
        id: "user-2",
        accessRole: AccessRole.NORMAL,
        avatarDisplay: { x: 0, y: 0, zoom: 1, rotation: 0 },
        favoriteWorks: [],
        name: "User",
        permissions: ["posts"],
        phrase: "",
        roles: ["reviewer"],
        status: "active",
        socials: [],
      },
    ];
    const dependencies = createDependencies({
      app,
      overrides: {
        SecurityEventSeverity: undefined,
        loadUsers: vi.fn(() => cloneJson(users)),
        getUserAccessContextById: vi.fn((userId) => {
          if (String(userId) === "owner-1") {
            return {
              accessRole: AccessRole.OWNER_PRIMARY,
              grants: { manage: true },
              isOwner: true,
              isPrimaryOwner: true,
            };
          }
          return {
            accessRole: AccessRole.NORMAL,
            grants: {},
            isOwner: false,
            isPrimaryOwner: false,
          };
        }),
        can: vi.fn(({ permissionId }) => permissionId === PermissionId.USUARIOS),
      },
    });

    registerUserManagementRoutes(dependencies);

    const route = getRoute(routes, "PUT", "/api/users/:id");
    const res = await invokeFinalHandler(route, {
      body: {
        permissions: ["analytics"],
      },
      params: { id: "user-2" },
      session: { user: { id: "owner-1" } },
    });

    expect(res.statusCode).toBe(200);
    expect(dependencies.emitSecurityEvent).toHaveBeenCalledWith(
      expect.objectContaining({
        type: "privilege_escalation_warning",
        severity: SecurityEventSeverity.WARNING,
      }),
    );
  });

  it("persists admin access role changes made by admins", async () => {
    const { app, routes } = createAppRecorder();
    const users = [
      {
        id: "admin-1",
        accessRole: AccessRole.ADMIN,
        avatarDisplay: { x: 0, y: 0, zoom: 1, rotation: 0 },
        favoriteWorks: [],
        permissions: [PermissionId.USUARIOS],
        roles: [],
        status: "active",
        socials: [],
      },
      {
        id: "user-2",
        accessRole: AccessRole.NORMAL,
        avatarDisplay: { x: 0, y: 0, zoom: 1, rotation: 0 },
        favoriteWorks: [],
        permissions: [PermissionId.POSTS],
        roles: ["reviewer"],
        status: "active",
        socials: [],
      },
    ];
    const persistCurrentUsers = vi.fn(({ users }) => users);
    const dependencies = createDependencies({
      app,
      overrides: {
        loadUsers: vi.fn(() => cloneJson(users)),
        persistCurrentUsers,
        getUserAccessContextById: vi.fn((userId) => {
          if (String(userId) === "admin-1") {
            return {
              accessRole: AccessRole.ADMIN,
              grants: { usuarios: true },
              isOwner: false,
              isPrimaryOwner: false,
            };
          }
          return {
            accessRole: AccessRole.NORMAL,
            grants: {},
            isOwner: false,
            isPrimaryOwner: false,
          };
        }),
        can: vi.fn(({ permissionId }) => permissionId === PermissionId.USUARIOS),
        userWithAccessForResponse: vi.fn((user) => ({
          ...user,
          grants: { usuarios: user.accessRole === AccessRole.ADMIN },
        })),
      },
    });

    registerUserManagementRoutes(dependencies);

    const route = getRoute(routes, "PUT", "/api/users/:id");
    const res = await invokeFinalHandler(route, {
      body: {
        accessRole: AccessRole.ADMIN,
        roles: ["reviewer"],
        status: "active",
      },
      params: { id: "user-2" },
      session: { user: { id: "admin-1" } },
    });

    expect(res.statusCode).toBe(200);
    expect(persistCurrentUsers).toHaveBeenCalledWith(
      expect.objectContaining({
        users: expect.arrayContaining([
          expect.objectContaining({
            id: "user-2",
            accessRole: AccessRole.ADMIN,
            roles: ["reviewer"],
            status: "active",
            permissions: [PermissionId.POSTS],
          }),
        ]),
      }),
    );
    expect(res.body.user).toEqual(
      expect.objectContaining({
        id: "user-2",
        accessRole: AccessRole.ADMIN,
      }),
    );
  });

  it("blocks secondary owners from deleting other owners", async () => {
    const { app, routes } = createAppRecorder();
    const users = [
      { id: "owner-1", accessRole: AccessRole.OWNER_PRIMARY, status: "active" },
      { id: "owner-2", accessRole: AccessRole.OWNER_SECONDARY, status: "active" },
      { id: "user-1", accessRole: AccessRole.NORMAL, status: "active" },
    ];
    const dependencies = createDependencies({
      app,
      overrides: {
        loadUsers: vi.fn(() => cloneJson(users)),
        getUserAccessContextById: vi.fn((userId) => {
          if (String(userId) === "owner-2") {
            return {
              accessRole: AccessRole.OWNER_SECONDARY,
              grants: { manage: true },
              isOwner: true,
              isPrimaryOwner: false,
            };
          }
          if (String(userId) === "owner-1") {
            return {
              accessRole: AccessRole.OWNER_PRIMARY,
              grants: { manage: true },
              isOwner: true,
              isPrimaryOwner: true,
            };
          }
          return {
            accessRole: AccessRole.NORMAL,
            grants: {},
            isOwner: false,
            isPrimaryOwner: false,
          };
        }),
        can: vi.fn(({ permissionId }) => permissionId === PermissionId.USUARIOS),
      },
    });

    registerUserManagementRoutes(dependencies);

    const route = getRoute(routes, "DELETE", "/api/users/:id");
    const res = await invokeFinalHandler(route, {
      params: { id: "owner-1" },
      session: { user: { id: "owner-2" } },
    });

    expect(res.statusCode).toBe(403);
    expect(res.body).toEqual({ error: "cannot_delete_primary_owner" });
    expect(dependencies.persistCurrentUsers).not.toHaveBeenCalled();
  });

  it("deletes a managed user through RBAC v2 and audits the removed snapshot", async () => {
    const { app, routes } = createAppRecorder();
    let storedUsers = [
      {
        id: "owner-1",
        name: "Owner",
        phrase: "",
        bio: "",
        email: "owner@example.com",
        accessRole: AccessRole.OWNER_PRIMARY,
        status: "active",
        order: 0,
      },
      {
        id: "user-1",
        name: "User",
        phrase: "",
        bio: "",
        email: "user@example.com",
        accessRole: AccessRole.NORMAL,
        status: "active",
        order: 1,
      },
    ];
    let ownerIds = ["owner-1"];
    const dependencies = createDependencies({
      app,
      overrides: {
        loadUsers: vi.fn(() => cloneJson(storedUsers)),
        normalizeUsers: vi.fn((users) => users),
        loadOwnerIds: vi.fn(() => ownerIds),
        writeOwnerIds: vi.fn((nextOwnerIds) => {
          ownerIds = nextOwnerIds;
        }),
        getUserAccessContextById: vi.fn((id) => ({
          accessRole: id === "owner-1" ? AccessRole.OWNER_PRIMARY : AccessRole.NORMAL,
          grants: id === "owner-1" ? { manage: true } : {},
          isOwner: id === "owner-1",
          isPrimaryOwner: id === "owner-1",
        })),
        persistCurrentUsers: vi.fn(({ users }) => {
          storedUsers = cloneJson(users);
          return users;
        }),
        userWithAccessForResponse: vi.fn((user) => ({ ...user, access: "scoped" })),
      },
    });

    registerUserManagementRoutes(dependencies);

    const route = getRoute(routes, "DELETE", "/api/users/:id");
    const res = await invokeFinalHandler(route, {
      params: { id: "user-1" },
      session: { user: { id: "owner-1" } },
    });

    expect(res.statusCode).toBe(200);
    expect(res.body).toEqual({ ok: true, ownerIds: ["owner-1"], primaryOwnerId: "owner-1" });
    expect(dependencies.persistCurrentUsers).toHaveBeenCalledWith({
      users: [expect.objectContaining({ id: "owner-1" })],
    });
    expect(dependencies.appendAuditLog).toHaveBeenCalledWith(
      expect.anything(),
      "users.delete",
      "users",
      expect.objectContaining({
        id: "user-1",
        wasOwner: false,
        before: expect.objectContaining({ id: "user-1", access: "scoped" }),
      }),
    );
  });
});
